app/main.py
"""
A builder for the Flask application. This should collate any app blueprints,
configuration variables, etc that the application needs
"""


from flask import Flask

from .routes import routes


def build():
    """
    build an instance of our Flask app
    """
    app = Flask(__name__)
    app.register_blueprint(routes)
    return app

app/routes.py
"""
create a Flask blueprint for our routes
"""

import os
import sqlite3

from datetime import datetime
from typing import Optional

import requests

from flask import Blueprint, json, request
from flask.templating import render_template

from . import storage
from .config import DB_PATH

routes = Blueprint("routes", __name__)


@routes.route("/ping")
def ping():
    """
    this is just for testing and healthchecks
    """
    return json.jsonify({"pong": datetime.now()})


@routes.route("/")
def index():
    """
    return just a basic welcome page with links to the two pages we offer
    """
    return render_template("index.html")


@routes.route("/call/")
@routes.route("/call/<string:room_name>")
def start_call_page(room_name: Optional[str] = None):
    # TODO: pull the base URL out into a configurable variable
    room_url = (
        "https://rory.daily.co/{}".format(room_name) if room_name is not None else None
    )
    return render_template("call.html", roomUrl=room_url)


@routes.route("/create_call")
def create_call():
    """
    create a daily call and return the url
    """
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer {}".format(os.environ.get("DAILY_API_KEY")),
    }
    resp = requests.post("https://api.daily.co/v1/rooms", headers=headers)
    return json.jsonify({"roomUrl": resp.json()["url"]})


@routes.route("/stats/")
def show_stats():
    """
    return a rendered "stats" template that shows all calls for which we have
    data available
    """
    with sqlite3.connect(DB_PATH) as db:
        return render_template("stats.html", calls=storage.get_calls(db))


@routes.route("/stats/<string:session_id>")
def get_stats_for_session(session_id):
    with sqlite3.connect(DB_PATH) as db:
        return json.jsonify(storage.get_stats_for_call(db, session_id).to_json())


@routes.route("/stats/", methods=["POST"])
def post_stats():
    """
    accept a stats JSON payload and store the values
    """
    data = request.json
    print(data)
    metrics = storage.stats_to_metrics(data)
    # we're connecting to sqlite3 here because SQLite's default behavior is
    # to require all insert operations occur within the same thread!
    with sqlite3.connect(DB_PATH) as db:
        storage.log_stats(db, metrics)
    return json.jsonify({"success": True}), 200, {"ContentType": "application/json"}

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <script crossorigin src="https://unpkg.com/@daily-co/daily-js"></script>
</head>

<body>
    {% block content %}
    {% endblock %}
</body>

</html>

app/templates/call.html
{% extends "base.html" %}

{% block content %}
<button id="start-call" onclick="startCallAndJoin()">start call</button>
<p id="call-share-text" style="visibility: hidden">
    Share this link to have others join your call!<br>
    <a id="call-url"></a>
</p>
<script src="{{ url_for('static', filename='call.js') }}"></script>
<script>
    // one benefit of this templating is that we can rely on the server to tell
    // us what the full Daily URL is. Otherwise, we'd have to hardcode
    // "https://rory.daily.co"
    // (or find another way to communicate the Daily URL to the frontend)
    let dailyUrl = {% if roomUrl is not none %} "{{roomUrl}}" {% else %} undefined {% endif %};
    let callFrame, roomName, sessionId;
    dailyUrl && joinCall(dailyUrl);
</script>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html>

<body>
    <h3>Hello! Welcome to Rory's Video Call Service (working title)</h3>
    <p>Please visit one or both of our two pages:</p>
    <p>- <a href="{{ url_for('routes.start_call_page') }}">video calls</a></p>
    <p>- <a href="{{ url_for('routes.show_stats') }}">video call statistics</a></p>
</body>

</html>

app/templates/stats.html
{% extends "base.html" %}

{% block content %}
<label for="call-select">choose a call, see some stats:</label>
<select id="call-select">
    <option selected value="skip">select a call from this list</option>
    {% for call in calls %}
    <option value="{{ call }}">{{ call }}</option>
    {% endfor %}
</select>

<div id="chart-container">
    <div class="video-send-bps-container">
        <label>videoSendBitsPerSecond</label>
        <div id="videoSendBitsPerSecond" class="plot"></div>
    </div>
    <div class="video-recv-bps-container">
        <label>videoRecvBitsPerSecond</label>
        <div id="videoRecvBitsPerSecond" class="plot"></div>
    </div>
    <div class="video-send-loss">
        <label>videoSendPacketLoss</label>
        <div id="videoSendPacketLoss" class="plot"></div>
    </div>
    <div class="video-recv-loss">
        <label>videoRecvPacketLoss</label>
        <div id="videoRecvPacketLoss" class="plot"></div>
    </div>
</div>
<script src="https://cdn.plot.ly/plotly-2.3.0.min.js"></script>
<script src="{{ url_for('static', filename='stats.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='stats.css') }}">
{% endblock %}